version: '3.3'
services:
  bot:
    build: .
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'sergiobot'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'bot'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'passwordRoot'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    # expose:
    # # Opens port 3306 on the container
    #   - '3306'
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    command: redis-server --loglevel warning
    volumes: 
      - cache:/data
# Names our volume
volumes:
  my-db:
  cache:
    driver: local